---
project_name: clipboard-sync
before:
    hooks:
      - go mod download
builds:
  - id: "linux-amd64"
    main: ./main.go
    binary: clipboard-sync
    ldflags:
      - -s -w -X main.version={{.Version}}
    env:
      - CGO_ENABLED=1
      - CC=gcc
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -tags=netgo
  - id: "linux-arm64"
    main: ./main.go
    binary: clipboard-sync
    ldflags:
      - -s -w -X main.version={{.Version}}
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
    goos:
      - linux
    goarch:
      - arm64
    flags:
      - -tags=netgo
archives:
  - name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - README.md
      - LICENSE
checksum:
    name_template: "checksum.txt"
snapshot:
    name_template: "{{ .Tag }}-next"
changelog:
    sort: asc
    use: github-native

release:
  prerelease: false
  make_latest: true

git:
  prerelease_suffix: "-"